-- LeanNCD: a Lean 4 encoding of the D-graded colored PROP framework.
-- Modules are imported here as they are implemented (see the Milestone A plan).
import LeanNCD.Base.Category
import LeanNCD.Base.Numeric
import LeanNCD.Base.ColoredPROP
import LeanNCD.Base.St
import LeanNCD.Base.Br
import LeanNCD.Seam.Adapter
import LeanNCD.Core.Graded
import LeanNCD.Core.Weave
import LeanNCD.Mixins.Temporal
import LeanNCD.Mixins.Route
import LeanNCD.Mixins.Symmetry
import LeanNCD.Grothendieck.Split
import LeanNCD.Algebra.Target
import LeanNCD.Algebra.Algebra
import LeanNCD.Props.Generic
import LeanNCD.Instances.StBr
import LeanNCD.Exec.Uid
import LeanNCD.Exec.Traversable
import LeanNCD.Exec.Context
import LeanNCD.DSL.SizeExpr
import LeanNCD.DSL.Ast
import LeanNCD.DSL.Syntax
import LeanNCD.DSL.Elab
import LeanNCD.DSL.Target
import LeanNCD.DSL.Traverse
import LeanNCD.DSL.Pipeline.Types
import LeanNCD.DSL.Pipeline.Structural
import LeanNCD.DSL.Pipeline.Lowering
import LeanNCD.DSL.Compile
import LeanNCD.Bridge.Realize
import LeanNCD.Bridge.SBr
import LeanNCD.Bridge.Agreement
import LeanNCD.Acset.SBrInstance
import LeanNCD.Acset.Csv
import LeanNCD.Acset.Io
