# Claude Opus 5 (1M context), effort high, wrote the wording.
# Claude Fable 5.1, effort 80, moved it into `block_titles_and_descriptions.json`.
'''Every block title and every block description of DeepSeek-V4.1-Flash.

A title heads a block in a figure and a description fills its inspection box. Both are
prose a reader sees. The wording is held in `block_titles_and_descriptions.json` beside
this module, one entry per name, and `BlockTitlesAndDescriptions` names every entry as
a field, so that a module reads `text.CORE_TITLE` with the name checked and typed, and
the file is edited, copied and translated with no Python in the way. The modules under
`notebooks/sota/DeepSeekV41Flash/` import `TEXT` as `text` and name a field of it where the string used to stand.

The file is read by `utilities/wording_json.py`, which states its form. A sentence
shared by several descriptions is one entry, and each description holding it names
it as `$NAME`, so that a change to the sentence reaches every box. A description
composed by a module from a layer number or a size is an entry with a field in braces,
and the module fills it at the call with `.format`. A formula stays beside the algebra
that builds it, because a formula is written from the axes of its morphism and is not
prose. The entries are grouped by mechanism, in the order the model is built, and the
fields below follow the same order.

`load` refuses a file whose names differ from the fields, through
`wording_json.load_dataclass`, so a name written in the file and nowhere else, or
removed from the file and still read, is found at import. A second wording file, holding the entries it
changes, is a localisation of a page, per `websocket_transfer/localise_descriptions.py`.
'''
from __future__ import annotations

import pathlib
from dataclasses import dataclass

import utilities.wording_json as wording_json

WORDING_FILE = pathlib.Path(__file__).with_suffix('.json')


@dataclass(frozen=True)
class BlockTitlesAndDescriptions:
    CORE_TITLE: str
    SOFTMAX_STEPS_SENTENCE: str
    CORE_DESCRIPTION: str
    WINDOW_CORE_DESCRIPTION: str
    TWO_BRANCH_DESCRIPTION: str

    FULL_TITLE: str
    REINDEX_TITLE: str
    REUSE_TITLE: str
    WINDOW_TITLE: str
    ENCODER_FULL_ATTENTION_DESCRIPTION: str
    DECODER_FULL_ATTENTION_DESCRIPTION: str
    REINDEX_ATTENTION_DESCRIPTION: str
    REUSE_ATTENTION_DESCRIPTION: str
    WINDOW_ATTENTION_DESCRIPTION: str

    POOL_TITLE: str
    SCORES_INTO_DISTANCES_SENTENCE: str
    SELECT_CANDIDATE_BLOCKS_OF_ONE_TOKEN_DESCRIPTION: str

    OUTPUT_TITLE: str
    PROJECT_ONE_QUERY_DESCRIPTION: str

    INDEXER_TITLE: str
    SCORE_TITLE: str
    GATHER_TITLE: str
    SCORE_EVERY_QUERY_DESCRIPTION: str
    GATHER_DESCRIPTION: str
    RELATIVE_INDEXER_DESCRIPTION: str

    COMPRESSOR_TITLE: str
    POOL_TOKENS_INTO_ENTRIES_DESCRIPTION: str
    PROJECT_TOKENS_INTO_ENTRIES_DESCRIPTION: str

    EXPERTS_TITLE: str
    GATE_TITLE: str
    SHARED_TITLE: str
    MIXTURE_TITLE: str
    EXPERT_BODY_CLAUSE: str
    ROUTED_EXPERTS_DESCRIPTION: str
    SHARED_EXPERT_DESCRIPTION: str
    MIX_ONE_TOKEN_DESCRIPTION: str
    EXPERT_GATE_DESCRIPTION: str

    SINKHORN_TITLE: str
    COEFFICIENTS_TITLE: str
    MHC_TITLE: str
    PREDICT_ONE_TOKEN_DESCRIPTION: str
    MHC_SUBLAYER_DESCRIPTION: str
    SINKHORN_DESCRIPTION: str

    MIXTURE_SUBLAYER_CLAUSE: str
    SLIDING_WINDOW_SUBLAYERS_CLAUSE: str
    ENCODER_GROUP_LAYERS_CLAUSE: str
    REINDEX_GROUP_LAYERS_CLAUSE: str
    SWA_BLOCK_DESCRIPTION: str
    ENCODER_REUSE_BLOCK_DESCRIPTION: str
    ENCODER_GROUP_DESCRIPTION: str
    DECODER_REUSE_BLOCK_DESCRIPTION: str
    REINDEX_REUSE_BLOCK_DESCRIPTION: str
    REINDEX_GROUP_DESCRIPTION: str

    EMBED_DESCRIPTION: str
    UNEMBED_DESCRIPTION: str

    SELECT_DESCRIPTION: str
    INDEX_SELECT_DESCRIPTION: str
    EMBEDDING_DESCRIPTION: str
    CONCATENATE_AXES_DESCRIPTION: str
    MERGED_POSITIONS_DESCRIPTION: str
    WINDOW_VIEW_DESCRIPTION: str
    GROUP_VIEW_DESCRIPTION: str
    BACK_VIEW_DESCRIPTION: str
    POSITION_VIEW_DESCRIPTION: str
    BLOCK_VIEW_DESCRIPTION: str

    SCORE_SCALE_SENTENCE: str
    SCALED_CORE_DESCRIPTION: str
    SCALED_WINDOW_CORE_DESCRIPTION: str

    TOKEN_TITLE: str
    ROTARY_OUTPUT_TITLE: str
    ENCODER_ENTRY_TITLE: str
    DECODER_ENTRY_TITLE: str
    INDEXER_QUERY_TITLE: str
    ENCODER_KEY_TITLE: str
    DECODER_KEY_TITLE: str
    PAIRS_OF_A_LATENT: str
    PAIRS_OF_AN_INDEXER_VECTOR: str
    TURN_BY_THE_TOKEN: str
    SCORE_BY_DISTANCE: str
    REST_OF_A_LATENT: str
    REST_OF_AN_INDEXER_VECTOR: str
    TABLE_IN_THE_BOX: str
    CONJUGATE_AFTER_THE_TABLE: str
    EXPLAIN_CHANNEL_JOIN_DESCRIPTION: str
    PAIRS_AS_COMPLEX_DESCRIPTION: str
    DECOMPLEX_DESCRIPTION: str
    TOKEN_LATENTS_DESCRIPTION: str
    ATTENTION_OUTPUT_DESCRIPTION: str
    ENCODER_ENTRIES_DESCRIPTION: str
    DECODER_ENTRIES_DESCRIPTION: str
    INDEXER_QUERIES_DESCRIPTION: str
    ENCODER_INDEXER_KEYS_DESCRIPTION: str
    DECODER_INDEXER_KEYS_DESCRIPTION: str

    ROTATED_SCORE_EVERY_QUERY_DESCRIPTION: str
    ROTATED_RELATIVE_INDEXER_DESCRIPTION: str

    ENTRY_TITLE: str
    QUANTISED_INDEXER_TITLE: str
    QUANTISED_WINDOW_TITLE: str
    CEILING_DESCRIPTION: str
    SCALE_GROUP_SPLIT_DESCRIPTION: str
    CHANNEL_GROUPS_SENTENCE: str
    ROUND_EVERY_GROUP_SENTENCE: str
    E2M1_NUMBERS_SENTENCE: str
    POWER_OF_TWO_SCALE_SENTENCE: str
    SCALE_ROUNDING_SENTENCES: str
    ENTRY_ROUND_TRIP_DESCRIPTION: str
    INDEXER_ROUND_TRIP_DESCRIPTION: str
    WINDOW_ROUND_TRIP_DESCRIPTION: str
    CAST_INTO_DESCRIPTION: str
    CAST_OUT_OF_DESCRIPTION: str

    PIN_TITLE: str
    PIN_NEWEST_BLOCK_DESCRIPTION: str
    PINNED_SELECT_CANDIDATE_BLOCKS_OF_ONE_TOKEN_DESCRIPTION: str

    ROTATED_AND_ROUNDED: str
    SCALED_AND_ROTATED_BACK: str
    SCORE_AND_ATTEND_SENTENCE: str
    SCALED_ENCODER_FULL_ATTENTION_DESCRIPTION: str
    SCALED_DECODER_FULL_ATTENTION_DESCRIPTION: str
    SCALED_REINDEX_ATTENTION_DESCRIPTION: str
    SCALED_REUSE_ATTENTION_DESCRIPTION: str
    SCALED_WINDOW_ATTENTION_DESCRIPTION: str

    TEMPERED_ROUTED_EXPERTS_DESCRIPTION: str
    TEMPERED_SHARED_EXPERT_DESCRIPTION: str
    MIXTURE_ENTRY_SENTENCE: str
    SUM_UNDER_GATES_SENTENCE: str
    TEMPERED_MIX_ONE_TOKEN_DESCRIPTION: str
    GATE_TEMPERATURE_SENTENCES: str
    GATE_SIGN_AND_NORMALISATION_SENTENCES: str
    TEMPERED_EXPERT_GATE_DESCRIPTION: str

    FIRST_ROUND_TITLE: str
    LATER_ROUND_TITLE: str
    FIRST_SINKHORN_ROUND_DESCRIPTION: str
    LATER_SINKHORN_ROUNDS_DESCRIPTION: str
    EPSILON_PREDICT_ONE_TOKEN_DESCRIPTION: str
    EPSILON_MHC_SUBLAYER_DESCRIPTION: str

    TOKEN_MAP_TITLE: str
    HASH_TITLE: str
    TABLE_TITLE: str
    ENGRAM_GATE_TITLE: str
    MAP_TOKENS_TO_COMPRESSED_IDENTIFIERS_DESCRIPTION: str
    ENGRAM_GATE_SENTENCES: str
    GATE_EVERY_STREAM_DESCRIPTION: str
    ENGRAM_GATE_WITHOUT_THE_MODALITY_DESCRIPTION: str
    ENGRAM_MODULE_SENTENCES: str
    ENGRAM_LAYERS_SENTENCE: str
    ENGRAM_BLOCK_DESCRIPTION: str
    ENGRAM_MODULE_OF_LAYER_DESCRIPTION: str
    ENGRAM_TABLE_DESCRIPTION: str
    NGRAM_TABLE_ROW_DESCRIPTION: str
    HASH_WRITTEN_OUT_DESCRIPTION: str
    HASH_OF_LAYER_SENTENCE: str
    HASH_CAST_DESCRIPTION: str
    HELD_IN_SENTENCE: str

    PATHWAY_TITLE: str
    ENCODER_TITLE: str
    PROJECTOR_TITLE: str
    CELL_WRITE_TITLE: str
    DELIMITER_WRITE_TITLE: str
    ENCODE_PATCHES_DESCRIPTION: str
    PROJECT_CELLS_DESCRIPTION: str
    WRITE_CELL_FEATURES_DESCRIPTION: str
    WRITE_SPAN_DELIMITERS_DESCRIPTION: str
    IMAGE_PATHWAY_DESCRIPTION: str

    DSPARK_TITLE: str
    TAP_TITLE: str
    BACKBONE_STATE_TITLE: str
    HEAD_TITLE: str
    SAMPLER_TITLE: str
    MARKOV_TITLE: str
    CONFIDENCE_TITLE: str
    STEP_TITLE: str
    CHAIN_TITLE: str
    DROP_STREAM_MEAN_DESCRIPTION: str
    PROJECT_STREAM_MEANS_DESCRIPTION: str
    HEAD_OVER_DRAFT_POSITIONS_DESCRIPTION: str
    SAMPLE_FROM_PROBABILITIES_DESCRIPTION: str
    MARKOV_HEAD_DESCRIPTION: str
    CONFIDENCE_HEAD_DESCRIPTION: str
    DRAFT_STEP_DESCRIPTION: str
    DRAFT_CHAIN_DESCRIPTION: str
    DSPARK_BLOCK_DESCRIPTION: str
    LAST_POSITION_DESCRIPTION: str
    ONLY_SLOT_DESCRIPTION: str
    DRAFT_POSITION_DESCRIPTION: str

    WINDOW_LAYER_TITLE: str
    REUSE_LAYER_TITLE: str
    TAPPED_REUSE_LAYER_TITLE: str
    ENCODER_GROUP_TITLE: str
    THIRD_ENCODER_GROUP_TITLE: str
    REINDEX_GROUP_TITLE: str
    FOURTH_REINDEX_GROUP_TITLE: str
    ENCODER_GROUPS_DESCRIPTION: str
    THIRD_GROUP_REUSE_BLOCK_DESCRIPTION: str
    THIRD_ENCODER_GROUP_DESCRIPTION: str
    REINDEX_GROUPS_DESCRIPTION: str
    FOURTH_REINDEX_GROUP_DESCRIPTION: str
    WINDOW_LAYER_DESCRIPTION: str
    TAPPED_REUSE_BLOCK_DESCRIPTION: str

    INPUTS_TITLE: str
    EMBEDDING_TITLE: str
    PUBLISH_IDENTIFIERS_AND_MODALITY_DESCRIPTION: str
    EMBED_TOKEN_IDENTIFIERS_DESCRIPTION: str

    TEXT_ONLY_ENGRAM_BLOCK_DESCRIPTION: str

    TEXT_ONLY_MIXTURE_MIX_ONE_TOKEN_DESCRIPTION: str
    TEXT_ONLY_MIXTURE_EXPERT_GATE_DESCRIPTION: str

    TEXT_ONLY_REINDEX_GROUPS_DESCRIPTION: str
    PUBLISH_IDENTIFIERS_DESCRIPTION: str

    VISION_ENCODER_DESCRIPTION: str
    DRAFT_TRUNK_DESCRIPTION: str
    EXPONENTIAL_DRAW_DESCRIPTION: str
    TOKEN_MAP_DESCRIPTION: str
    MARKOV_EMBEDDING_DESCRIPTION: str
    ONES_DESCRIPTION: str
    POSITIVE_INFINITY_DESCRIPTION: str
    INJECT_DESCRIPTION: str
    LOOKBACK_VIEW_DESCRIPTION: str
    PREFIX_VIEW_DESCRIPTION: str
    PRIMES_BEFORE_VIEW_DESCRIPTION: str
    PAIR_VIEW_DESCRIPTION: str

    QUERY_DOWN_PROJECTION_ROLE: str
    QUERY_UP_PROJECTION_ROLE: str
    WINDOW_LATENT_PROJECTION_ROLE: str
    SINK_LOGIT_ROLE: str
    OUTPUT_PROJECTION_FIRST_HALF_ROLE: str
    OUTPUT_PROJECTION_SECOND_HALF_ROLE: str
    ROUTER_ROLE: str
    CORRECTION_BIAS_ROLE: str
    EXPERT_GATE_PROJECTION_ROLE: str
    EXPERT_UP_PROJECTION_ROLE: str
    EXPERT_DOWN_PROJECTION_ROLE: str
    SHARED_GATE_PROJECTION_ROLE: str
    SHARED_UP_PROJECTION_ROLE: str
    SHARED_DOWN_PROJECTION_ROLE: str
    COMPRESSOR_VALUE_PROJECTION_ROLE: str
    COMPRESSOR_GATE_PROJECTION_ROLE: str
    INDEXER_KEY_PROJECTION_ROLE: str
    INDEXER_QUERY_PROJECTION_ROLE: str
    INDEXER_HEAD_WEIGHTS_ROLE: str
    COLLAPSE_PROJECTION_ROLE: str
    OUTPUT_VECTOR_PROJECTION_ROLE: str
    COMBINE_PROJECTION_ROLE: str
    OUTPUT_HEAD_ROLE: str

    ENGRAM_KEY_PROJECTION_ROLE: str
    ENGRAM_VALUE_PROJECTION_ROLE: str
    ENGRAM_GATE_WEIGHT_ROLE: str
    ENGRAM_MULTIPLIERS_ROLE: str
    ENGRAM_PRIMES_ROLE: str

    SQRT_SOFTPLUS_ROLE: str
    ROUTE_SCALE_ROLE: str
    SILU_ROLE: str
    COLLAPSE_SIGMOID_ROLE: str
    OUTPUT_DOUBLED_SIGMOID_ROLE: str
    NORMALISING_RECIPROCAL_ROLE: str
    ENGRAM_STREAM_GATE_ROLE: str
    ENGRAM_GATE_ROLE: str
    RMSNORM_ROLE: str
    SCORE_SCALE_ROLE: str
    INDEXER_HEAD_SCALE_ROLE: str
    GATE_LIMIT_ROLE: str
    UP_LIMIT_ROLE: str
    TEMPERATURE_ROLE: str
    MODALITY_BIAS_ROLE: str
    MHC_EPSILON_ROLE: str

    TOP_K_WEIGHTS_DESCRIPTION: str
    TOP_K_WEIGHTS_SELECT_DESCRIPTION: str
    TOP_K_ONLY_WEIGHTS_DESCRIPTION: str
    TOP_K_ONLY_SELECTION_DESCRIPTION: str
    TOP_K_OVER_POSITIONS_SENTENCE: str
    COVARIANT_VIEW_WRITES_EACH_SENTENCE: str
    COVARIANT_VIEW_WRITES_ONE_SENTENCE: str
    COVARIANT_VIEW_WRITES_INPUT_SENTENCE: str
    COVARIANT_VIEW_BROADCAST_SENTENCE: str
    COVARIANT_VIEW_UNIT_SENTENCE: str

    MAGNITUDE_ROLE: str
    SCALE_BY_SIX_ROLE: str
    SCALE_BY_448_ROLE: str
    SCALE_FLOOR_E4M3_ROLE: str
    SCALE_FLOOR_E8M0_ROLE: str
    MAGNITUDE_FLOOR_ROLE: str
    LOG2_SCALE_ROLE: str
    CLAMP_E2M1_ROLE: str
    CLAMP_E4M3_ROLE: str
    E2M1_STORED_NUMBERS: str
    E4M3_STORED_NUMBERS: str

    WINDOW_ROTARY_TABLE_ROLE: str
    YARN_ROTARY_TABLE_ROLE: str

    GELU_ROLE: str
    PROJECTOR_FIRST_MAP_ROLE: str
    PROJECTOR_SECOND_MAP_ROLE: str
    DELIMITER_VECTORS_ROLE: str
    MAIN_PROJECTION_ROLE: str
    MARKOV_PROJECTION_ROLE: str
    CONFIDENCE_STATE_HALF_ROLE: str
    CONFIDENCE_MARKOV_HALF_ROLE: str

    FIRST_WINDOW_LAYER_SENTENCE: str
    SECOND_WINDOW_LAYER_SENTENCE: str

    ROUNDING_KERNEL_DESCRIPTION: str
    FILE_QUANTISATION_SENTENCE: str
    WEIGHT_QUANTISATION_SENTENCE: str

    @classmethod
    def load(cls, path: pathlib.Path = WORDING_FILE) -> BlockTitlesAndDescriptions:
        return wording_json.load_dataclass(cls, path)


TEXT = BlockTitlesAndDescriptions.load()
