# ops.Linear is an opaque operator. Its signature states "N inputs map to M outputs"
# with a trivial (empty) reindexing, so nothing about its output ever shows
# up in a dependency reading of the graph - from the graph's point of view its
# output axes come from nowhere. This
# expands a Linear into its explicit form: a 0-input "weight" array
# (generated by a 0 -> (inputs + outputs) Linear) contracted against the
# real input via an Einops, so the output axes are wired in through a real
# reindexing like everything else.
#
# A Linear embedded in a larger expression is usually broadcast over extra
# degree axes it does not itself consume. In a convolution, built
# as a reindexing followed by a k,cin -> cout Linear, the Linear is
# broadcast over the output-position axis x' (per Weaves, Wires, and
# Morphisms, Section 4.3). target.dom()/.cod() report the *lifted* shape,
# degree axes included, so the real (pre-broadcast) input/output shape has
# to come from each weave's own .target() instead. The replacement is then
# re-lifted over the same degree via construction_helpers.lift, so it
# broadcasts exactly like the Linear it replaces.

from __future__ import annotations
from dataclasses import dataclass
import data_structure.Term as fd
import data_structure.Category as cat
import data_structure.Operators as ops

import construction_helpers.lift as chl
import graphs.processing.hypergraph_functor as functor
from term_utilities import term_utilities as tutil

from construction_helpers import simple_helper as chsh

import algebra.node_expansion as node_expansion
import algebra.registries.standard_expansions as standard_expansions
import para.processing.write_linear_formula as write_linear_formula


def _axis_name(axis: cat.Axis, fallback: str) -> str:
    if axis.uid._name is not None:
        return axis.uid._name.to_bodies()
    return fallback

# `expand_to_nodes` moved to `algebra.node_expansion`, because `para` needs it too,
# to reverse a reindexing on its own and take the core's derivative on a
# cleanly broadcast operator. Re-exported here under its old name.
expand_to_nodes = node_expansion.expand_to_nodes

def expand_linear_root[B: cat.Datatype](
    target: cat.Broadcasted[B, cat.RawAxis]
) -> cat.ProdCategory[cat.Array[B, cat.RawAxis], cat.Broadcasted[B, cat.RawAxis]]:
    '''A `Linear` as a weight array contracted against its input by an `Einops`.

    A `Linear` that selects is returned unchanged. `ops.selects_weights` states
    why: the expansion writes the contraction `dom_target, dom_target x
    cod_target -> cod_target`, and an index operand is not one of the axes
    being summed over. Expanding it would contract the selection axis away and
    give an average of every weight where one weight was meant.

    A `Linear` with no input is a weight array already, and a `Linear` with
    several inputs is the parametrised form of `para.show_grabbed_parameters`,
    whose weight is an operand on a wire. Neither has an implicit weight to
    move out, so both are returned unchanged.
    '''
    if (not isinstance(target.operator, ops.Linear) or ops.selects_weights(target)
            or len(target.input_weaves) != 1):
        return target
    nodes, new_core = expand_to_nodes(target)
    degree = target.degree()
    dom_weave = target.input_weaves[0]
    cod_weave = target.output_weaves[0]
    new_degree = tuple(target.degree()) + tuple(cod_weave.target().shape())
    # The weight's contracted axes are named in the same order the weight array
    # below declares them. Reversing both the signature and this weave (as this
    # used to) contracts the right pairs, but leaves the array on the wire
    # transposed with respect to the one the weight block produces, which is harmless
    # while the weight block stays outside the kernel, and a mismatched meeting
    # point the moment it does not (fuse_chain with a fusable that admits it).
    signature = tuple(range(len(dom_weave.target().shape())))
    einops = cat.Broadcasted(
        operator=ops.Einops(signature=(signature, signature)),
        input_weaves=(
            dom_weave,
            cat.Weave(
                dom_weave.datatype,
                tuple(dom_weave.target().shape())
                  + (cat.WeaveMode.TILED,) * len(cod_weave.target().shape())
            )),
        output_weaves=(
            cat.Weave(
                dom_weave.datatype,
                (cat.WeaveMode.TILED,) * len(new_degree)
            ),
        ),
        reindexings=(
            cat.Rearrangement(tuple(range(len(degree))), new_degree),
            cat.Rearrangement(tuple(range(len(degree), len(new_degree))), new_degree)
        )
    )
    new_linear = cat.Broadcasted(
        operator=target.operator,
        input_weaves=(),
        output_weaves=(
            cat.Weave(dom_weave.datatype, (*dom_weave.target().shape(), *cod_weave.target().shape())),
        ),
        reindexings=()
    )
    return chsh.make_composed(
        chsh.make_product(nodes, new_linear),
        einops
    )

@dataclass
class ExpandLinear[B: cat.Datatype](functor.Endofunctor[
    cat.Array[B, cat.RawAxis], cat.Broadcasted[B, cat.RawAxis],
]):
    def apply_root(self, target: cat.Broadcasted[B, cat.RawAxis]):
        return expand_linear_root(target)


def is_parametrised_linear(target: cat.Broadcasted) -> bool:
    '''Whether `target` is a `Linear` reading its weight from its first operand,
    its bias from its second where it has one, and one data operand after them,
    which is the form `para.show_grabbed_parameters` writes once the grab has
    become a weight array.'''
    if not isinstance(target.operator, ops.Linear) or ops.selects_weights(target):
        return False
    parameter_weaves = target.input_weaves[:-1]
    return (len(parameter_weaves) == (2 if target.operator.bias else 1)
            and not any(any(weave.select_degree(weave._shape))
                        for weave in parameter_weaves))


@standard_expansions.register(
    ops.Linear,
    formula=write_linear_formula.linear_formula,
    description=write_linear_formula.linear_description)
def expand_parametrised_linear_root[B: cat.Datatype](
    target: cat.Broadcasted[B, cat.RawAxis],
) -> cat.BroadcastedCategory[B, cat.RawAxis]:
    '''A parametrised `Linear` as the `Einops` that contracts its weight
    operand against its data operand, followed by the addition of its bias
    operand where it has one. Anything else comes back unchanged.

    The rule is registered as the standard expansion of a `Linear`. A `Linear`
    whose weight is still inside the operator comes back unchanged, so a caller
    that wants the contraction passes it through
    `para.processing.show_grabbed_parameters.grab_parameters` first, as
    `notebooks/display/expand_with_parameters.py` does for an inspection box.
    '''
    if not is_parametrised_linear(target):
        return target
    contraction = contract_weight_against_data(target)
    if not target.operator.bias:
        return contraction
    weight, bias, data = tuple(target.dom())
    return chsh.make_composed(
        cat.Rearrangement((0, 2, 1), (weight, bias, data)),
        chsh.make_product(contraction, cat.ProdObject((bias,)).identity()),
        add_bias_over_produced_axes(target))


def contract_weight_against_data[B: cat.Datatype](
    target: cat.Broadcasted[B, cat.RawAxis],
) -> cat.Broadcasted[B, cat.RawAxis]:
    '''The `Einops` that contracts the first operand of a parametrised `Linear`,
    its weight, against its last operand, its data.

    The weight operand keeps its wire, so the weight array it comes from is
    untouched. The `Einops` carries the `Linear`'s name, so a kernel cut can
    still name the contraction after the projection it performs. The result is
    the `Einops` that `expand_linear_root` writes for the implicit form, with
    the weight first among the operands, as `show_grabbed_parameters` orders
    them.
    '''
    weight_weave, data_weave = target.input_weaves[0], target.input_weaves[-1]
    data_reindexing = target.reindexings[-1]
    cod_weave = target.output_weaves[0]
    contracted = tuple(data_weave.target().shape())
    produced = tuple(cod_weave.target().shape())
    if tuple(weight_weave.target().shape()) != contracted + produced:
        raise ValueError(
            f'the weight of {target.operator.name} has the axes '
            f'{weight_weave.target().shape()} where its operand and result have '
            f'{contracted} and {produced}')
    degree = tuple(target.degree())
    new_degree = degree + produced
    signature = tuple(range(len(contracted)))
    return cat.Broadcasted(
        operator=ops.Einops(name=target.operator.name, signature=(signature, signature)),
        input_weaves=(
            cat.Weave(weight_weave.datatype,
                      contracted + (cat.WeaveMode.TILED,) * len(produced)),
            data_weave),
        output_weaves=(
            cat.Weave(cod_weave.datatype, (cat.WeaveMode.TILED,) * len(new_degree)),),
        reindexings=(
            cat.Rearrangement(tuple(range(len(degree), len(new_degree))), new_degree),
            cat.Rearrangement(data_reindexing.mapping, new_degree)))


def add_bias_over_produced_axes[B: cat.Datatype](
    target: cat.Broadcasted[B, cat.RawAxis],
) -> cat.Broadcasted[B, cat.RawAxis]:
    '''The addition of the bias operand of a parametrised `Linear` to the result
    of `contract_weight_against_data`. The result carries the degree of the
    `Linear` followed by the axes it produces, and the bias is read at the
    produced axes alone, so one bias value is added at every index of the degree.'''
    bias_weave = target.input_weaves[1]
    cod_weave = target.output_weaves[0]
    produced = tuple(cod_weave.target().shape())
    if tuple(bias_weave.target().shape()) != produced:
        raise ValueError(
            f'the bias of {target.operator.name} has the axes '
            f'{bias_weave.target().shape()} where its result has {produced}')
    degree = tuple(target.degree())
    new_degree = degree + produced
    return cat.Broadcasted(
        operator=ops.AdditionOp(),
        input_weaves=(
            cat.Weave(cod_weave.datatype, (cat.WeaveMode.TILED,) * len(new_degree)),
            cat.Weave(bias_weave.datatype, (cat.WeaveMode.TILED,) * len(produced))),
        output_weaves=(
            cat.Weave(cod_weave.datatype, (cat.WeaveMode.TILED,) * len(new_degree)),),
        reindexings=(
            cat.ProdObject(new_degree).identity(),
            cat.Rearrangement(tuple(range(len(degree), len(new_degree))), new_degree)))


@dataclass
class ExpandParametrisedLinear[B: cat.Datatype](functor.Endofunctor[
    cat.Array[B, cat.RawAxis], cat.Broadcasted[B, cat.RawAxis],
]):
    def apply_root(self, target: cat.Broadcasted[B, cat.RawAxis]):
        return expand_parametrised_linear_root(target)


def expand_parametrised_linears(target):
    '''Every parametrised `Linear` in a morphism or hypergraph replaced by the
    `Einops` that contracts its weight operand, and the addition of its bias
    operand where it has one.'''
    return ExpandParametrisedLinear()(target)


# ---------------------------------------------------------------------------
# Fusion policy for the EXPANDED form.
#
# After expand_linear_root, a Linear is a 0-input weight array in its own block.
# `is_fusable` is the predicate a pass that merges neighbouring operations should be
# given in that case: a Linear weight block is an isolated parameter array, so
# merging it into a real computation gains nothing and it stays standalone
# (reconnecting by node identity). It lives here, with the Linear concern, so the
# policy can be swapped without touching the merging mechanism.
#
# It is not the default of such a pass, because it is wrong for an unexpanded
# expression, because there a Linear is the computation and refusing it can leave
# nothing to fuse at all. Folding the weight block in *does* work
# (fuse_chain.fuse_everything on an expanded graph), and gives the same axes and
# roles. It is not the useful choice for a parameter array.
# ---------------------------------------------------------------------------
def contains_linear(graph) -> bool:
    '''True if `graph` wraps a Linear operator.'''
    return any(
        isinstance(root.operator, ops.Linear)
        for root in tutil.type_search(cat.Broadcasted, graph)
    )


def is_fusable(block) -> bool:
    '''Expanded-form fuse_chain policy: everything except a Linear weight block.'''
    return not contains_linear(block)
